"""Initial

Revision ID: e9c1236500a8
Revises: 
Create Date: 2026-06-03 13:09:53.698291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9c1236500a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('board', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_school_name')
    )
    op.create_table('academic_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_year')
    )
    op.create_index('idx_academic_year_school', 'academic_years', ['school_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_branch_school_id', 'branches', ['school_id'], unique=False)
    op.create_table('brandings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('school_name_display', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'grade', name='uq_grade_per_branch')
    )
    op.create_index('idx_class_branch_id', 'classes', ['branch_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'room_name', name='uq_room_per_branch')
    )
    op.create_index('idx_classroom_branch_id', 'classrooms', ['branch_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'trigger_type', 'channel', 'language', name='uq_template')
    )
    op.create_table('school_calendar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'date', name='uq_calendar_date')
    )
    op.create_index('idx_calendar_branch_date', 'school_calendar', ['branch_id', 'date'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('student_photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number', name='uq_student_admission')
    )
    op.create_index('idx_student_admission', 'students', ['admission_number'], unique=False)
    op.create_index('idx_student_branch_id', 'students', ['branch_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'name', name='uq_subject_per_branch')
    )
    op.create_index('idx_subject_branch_id', 'subjects', ['branch_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('totp_secret', sa.String(length=200), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('SUPER_ADMIN','ADMIN','TEACHER','STUDENT','PARENT','FEE_ADMIN')", name='check_user_role'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index('idx_user_branch_id', 'users', ['branch_id'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('review_remarks', sa.String(length=500), nullable=True),
    sa.Column('affects_attendance', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leave_status', 'leave_requests', ['status'], unique=False)
    op.create_index('idx_leave_student_year', 'leave_requests', ['student_id', 'academic_year_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notif_recipient', 'notifications', ['recipient_id'], unique=False)
    op.create_index('idx_notif_status', 'notifications', ['status'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('parent_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_number', name='uq_parent_contact'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_parent_contact', 'parents', ['contact_number'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='uq_section_per_class')
    )
    op.create_index('idx_section_class_id', 'sections', ['class_id'], unique=False)
    op.create_table('student_faces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('brightness_score', sa.Float(), nullable=True),
    sa.Column('face_angle_yaw', sa.Float(), nullable=True),
    sa.Column('face_angle_pitch', sa.Float(), nullable=True),
    sa.Column('face_angle_roll', sa.Float(), nullable=True),
    sa.Column('face_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('captured_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_face_student_id', 'student_faces', ['student_id'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'employee_id', name='uq_employee_id_per_branch'),
    sa.UniqueConstraint('user_id', name='uq_teacher_user_id')
    )
    op.create_index('idx_teacher_branch_id', 'teacher_profiles', ['branch_id'], unique=False)
    op.create_index('idx_teacher_user_id', 'teacher_profiles', ['user_id'], unique=False)
    op.create_table('academic_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('promotion_status', sa.String(length=20), nullable=False),
    sa.Column('final_attendance_pct', sa.Float(), nullable=True),
    sa.Column('total_present', sa.Integer(), nullable=True),
    sa.Column('total_working_days', sa.Integer(), nullable=True),
    sa.Column('subject_attendance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('marks_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_academic_record')
    )
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_number', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('rtsp_url', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('frame_sample_interval_secs', sa.Integer(), nullable=False),
    sa.Column('stream_status', sa.String(length=20), nullable=True),
    sa.Column('last_heartbeat', sa.TIMESTAMP(), nullable=True),
    sa.Column('reconnect_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rtsp_url', name='uq_camera_rtsp')
    )
    op.create_index('idx_camera_section_id', 'cameras', ['section_id'], unique=False)
    op.create_table('period_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'academic_year_id', 'day_of_week', 'period_number', name='uq_period_slot')
    )
    op.create_index('idx_period_slot_section_year', 'period_slots', ['section_id', 'academic_year_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.Column('exited_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'roll_number', 'academic_year_id', name='uq_roll_in_section_year'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_student_per_year')
    )
    op.create_index('idx_enroll_section', 'student_enrollments', ['section_id'], unique=False)
    op.create_index('idx_enroll_student', 'student_enrollments', ['student_id'], unique=False)
    op.create_index('idx_enroll_year', 'student_enrollments', ['academic_year_id'], unique=False)
    op.create_table('student_parents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'parent_id', name='uq_student_parent')
    )
    op.create_table('teacher_subject_eligibilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_profile_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_profile_id', 'subject_id', 'class_id', name='uq_teacher_subject_class')
    )
    op.create_index('idx_elig_class', 'teacher_subject_eligibilities', ['class_id'], unique=False)
    op.create_index('idx_elig_subject', 'teacher_subject_eligibilities', ['subject_id'], unique=False)
    op.create_index('idx_elig_teacher', 'teacher_subject_eligibilities', ['teacher_profile_id'], unique=False)
    op.create_table('timetable_frequency_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('target_per_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'academic_year_id', 'subject_id', name='uq_freq_target')
    )
    op.create_table('camera_health_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fps_actual', sa.Float(), nullable=True),
    sa.Column('frames_dropped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cam_health_cam_time', 'camera_health_logs', ['camera_id', 'logged_at'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_slot_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('teacher_profile_id', sa.UUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_slot_id'], ['period_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_slot_id', 'academic_year_id', name='uq_timetable_entry')
    )
    op.create_index('idx_tt_entry_slot', 'timetable_entries', ['period_slot_id'], unique=False)
    op.create_index('idx_tt_entry_teacher', 'timetable_entries', ['teacher_profile_id'], unique=False)
    op.create_table('attendance_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('timetable_entry_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.INTEGER()), nullable=False),
    sa.Column('is_manual_trigger', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_detections_required', sa.Integer(), nullable=False),
    sa.Column('min_presence_minutes', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('detection_start_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'name', name='uq_window_name_per_section')
    )
    op.create_index('idx_window_section_id', 'attendance_windows', ['section_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('attendance_window_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('first_detected_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_detected_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('captured_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('data_confidence', sa.String(length=20), nullable=True),
    sa.Column('marked_by', sa.String(length=20), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attendance_window_id'], ['attendance_windows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'attendance_window_id', 'attendance_date', name='uq_student_window_date')
    )
    op.create_index('idx_att_section_date', 'attendance', ['section_id', 'attendance_date'], unique=False)
    op.create_index('idx_att_student_year', 'attendance', ['student_id', 'academic_year_id'], unique=False)
    op.create_index('idx_att_window_date', 'attendance', ['attendance_window_id', 'attendance_date'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('attendance_window_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('tracking_id', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding_distance', sa.Float(), nullable=True),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('frame_brightness', sa.Float(), nullable=True),
    sa.Column('frame_quality_score', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=True),
    sa.Column('training_added_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attendance_window_id'], ['attendance_windows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detection_camera', 'detections', ['camera_id'], unique=False)
    op.create_index('idx_detection_section', 'detections', ['section_id'], unique=False)
    op.create_index('idx_detection_section_time', 'detections', ['section_id', 'detected_at'], unique=False)
    op.create_index('idx_detection_student', 'detections', ['student_id'], unique=False)
    op.create_index('idx_detection_window_time', 'detections', ['attendance_window_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_detection_window_time', table_name='detections')
    op.drop_index('idx_detection_student', table_name='detections')
    op.drop_index('idx_detection_section_time', table_name='detections')
    op.drop_index('idx_detection_section', table_name='detections')
    op.drop_index('idx_detection_camera', table_name='detections')
    op.drop_table('detections')
    op.drop_index('idx_att_window_date', table_name='attendance')
    op.drop_index('idx_att_student_year', table_name='attendance')
    op.drop_index('idx_att_section_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('idx_window_section_id', table_name='attendance_windows')
    op.drop_table('attendance_windows')
    op.drop_index('idx_tt_entry_teacher', table_name='timetable_entries')
    op.drop_index('idx_tt_entry_slot', table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index('idx_cam_health_cam_time', table_name='camera_health_logs')
    op.drop_table('camera_health_logs')
    op.drop_table('timetable_frequency_targets')
    op.drop_index('idx_elig_teacher', table_name='teacher_subject_eligibilities')
    op.drop_index('idx_elig_subject', table_name='teacher_subject_eligibilities')
    op.drop_index('idx_elig_class', table_name='teacher_subject_eligibilities')
    op.drop_table('teacher_subject_eligibilities')
    op.drop_table('student_parents')
    op.drop_index('idx_enroll_year', table_name='student_enrollments')
    op.drop_index('idx_enroll_student', table_name='student_enrollments')
    op.drop_index('idx_enroll_section', table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index('idx_period_slot_section_year', table_name='period_slots')
    op.drop_table('period_slots')
    op.drop_index('idx_camera_section_id', table_name='cameras')
    op.drop_table('cameras')
    op.drop_table('academic_records')
    op.drop_index('idx_teacher_user_id', table_name='teacher_profiles')
    op.drop_index('idx_teacher_branch_id', table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index('idx_face_student_id', table_name='student_faces')
    op.drop_table('student_faces')
    op.drop_index('idx_section_class_id', table_name='sections')
    op.drop_table('sections')
    op.drop_index('idx_parent_contact', table_name='parents')
    op.drop_table('parents')
    op.drop_index('idx_notif_status', table_name='notifications')
    op.drop_index('idx_notif_recipient', table_name='notifications')
    op.drop_index('idx_notif_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_leave_student_year', table_name='leave_requests')
    op.drop_index('idx_leave_status', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_branch_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_subject_branch_id', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('idx_student_branch_id', table_name='students')
    op.drop_index('idx_student_admission', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_calendar_branch_date', table_name='school_calendar')
    op.drop_table('school_calendar')
    op.drop_table('notification_templates')
    op.drop_index('idx_classroom_branch_id', table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index('idx_class_branch_id', table_name='classes')
    op.drop_table('classes')
    op.drop_table('brandings')
    op.drop_index('idx_branch_school_id', table_name='branches')
    op.drop_table('branches')
    op.drop_index('idx_academic_year_school', table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_table('schools')
    # ### end Alembic commands ###
